--Script that uses system views to retrieve the list of user tables, their estimated row counts, and their total space usage (including data and indexes) in Gigabytes.
--This script uses sys.dm_db_partition_stats which provides a good balance between accuracy and performance, as it reads metadata rather than scanning the tables directly.
-- ====================================================================================
-- Author:      [Generated by AI - Review Recommended]
-- Create date: [Current Date]
-- Description: Lists all user tables in the current database,
--              their total row count, and their total size (data + indexes) in GB.
-- Database:    Run this script in the context of the database you want to query.
-- Notes:
--   - Row counts are based on metadata and might not be 100% precise,
--     especially after many modifications without statistics updates.
--   - Size includes data pages, index pages, LOB pages, etc. associated
--     with the table. It represents the space *used*.
--   - Filters out Microsoft-shipped objects.
-- ====================================================================================

-- Use a CTE to calculate row counts (summing across partitions, specifically for heap/clustered index)
WITH TableRowCounts AS (
    SELECT
        ps.object_id,
        SUM(ps.row_count) AS TotalRowCount
    FROM
        sys.dm_db_partition_stats ps
    WHERE
        ps.index_id < 2 -- 0 = Heap, 1 = Clustered Index (these store the actual table rows)
    GROUP BY
        ps.object_id
),
-- Use a CTE to calculate total used pages (summing across all partitions and indexes for the table)
TableSpaceUsage AS (
    SELECT
        ps.object_id,
        SUM(ps.used_page_count) AS TotalUsedPages
    FROM
        sys.dm_db_partition_stats ps
    GROUP BY
        ps.object_id
)
-- Final SELECT combining table info, row counts, and space usage
SELECT
    s.name AS SchemaName,
    t.name AS TableName,
    ISNULL(trc.TotalRowCount, 0) AS RecordCount, -- Display 0 if no rows found in stats
    -- Calculate size in GB (1 page = 8 KB)
    CAST( (ISNULL(tsu.TotalUsedPages, 0) * 8.0 / 1024.0 / 1024.0) AS DECIMAL(18, 4) ) AS TotalSizeGB
FROM
    sys.tables t
INNER JOIN
    sys.schemas s ON t.schema_id = s.schema_id
LEFT JOIN
    TableRowCounts trc ON t.object_id = trc.object_id
LEFT JOIN
    TableSpaceUsage tsu ON t.object_id = tsu.object_id
WHERE
    t.type = 'U' -- User table
    AND t.is_ms_shipped = 0 -- Exclude Microsoft-shipped tables (e.g., diagram tables)
ORDER BY
    TotalSizeGB DESC, -- Show largest tables first
    SchemaName ASC,
    TableName ASC;

-- Optional: Add a summary row for the entire database (can be run separately)
/*
SELECT
    '-- TOTAL --' AS SchemaName,
    '-- TOTAL --' AS TableName,
    SUM(RecordCount) AS TotalRecordCount,
    SUM(TotalSizeGB) AS GrandTotalSizeGB
FROM (
    SELECT
        s.name AS SchemaName,
        t.name AS TableName,
        ISNULL(trc.TotalRowCount, 0) AS RecordCount,
        CAST( (ISNULL(tsu.TotalUsedPages, 0) * 8.0 / 1024.0 / 1024.0) AS DECIMAL(18, 4) ) AS TotalSizeGB
    FROM
        sys.tables t
    INNER JOIN
        sys.schemas s ON t.schema_id = s.schema_id
    LEFT JOIN (
        SELECT ps.object_id, SUM(ps.row_count) AS TotalRowCount
        FROM sys.dm_db_partition_stats ps WHERE ps.index_id < 2 GROUP BY ps.object_id
    ) trc ON t.object_id = trc.object_id
    LEFT JOIN (
        SELECT ps.object_id, SUM(ps.used_page_count) AS TotalUsedPages
        FROM sys.dm_db_partition_stats ps GROUP BY ps.object_id
    ) tsu ON t.object_id = tsu.object_id
    WHERE t.type = 'U' AND t.is_ms_shipped = 0
) AS DatabaseSummary;
*/

/*How to use it:
Open SQL Server Management Studio (SSMS) or Azure Data Studio.
Connect to the SQL Server instance containing the database you want to analyze.
Make sure the correct database context is selected in the dropdown list (or use a USE YourDatabaseName; statement before the script).
Paste the script into a new query window.
Execute the script (press F5 or click Execute).
Explanation:
sys.tables: This system view contains one row for each table object. We use it to get the table names (name) and their schema (schema_id).
sys.schemas: Joined to get the actual name of the schema (like dbo).
sys.dm_db_partition_stats: This Dynamic Management View (DMV) returns page and row-count information for every partition in the current database.
object_id: Links back to the table in sys.tables.
index_id: Identifies the index (0 for a heap, 1 for a clustered index, >1 for non-clustered indexes).
row_count: The approximate number of rows in the partition.
used_page_count: The number of 8KB pages actually used by the partition (includes data, index, LOB pages etc.).
TableRowCounts CTE: Calculates the sum of row_count for each table (object_id), but only for the partitions representing the base table data (index_id < 2). This avoids double-counting rows if non-clustered indexes exist.
TableSpaceUsage CTE: Calculates the sum of used_page_count for all partitions and indexes associated with a table (object_id). This gives the total space used by the table and its related structures.
Main SELECT: Joins the tables, schemas, row counts, and space usage together.
WHERE t.type = 'U': Filters to include only user tables (not system tables, views, etc.).
WHERE t.is_ms_shipped = 0: Excludes tables created by internal SQL Server features (like database diagrams).
Size Calculation: TotalUsedPages * 8.0 / 1024.0 / 1024.0 converts the total 8KB pages into Gigabytes. We use 8.0 and 1024.0 to ensure floating-point division for accuracy.
ISNULL(..., 0): Used to display 0 for row count or size if a table exists but somehow has no corresponding entries in sys.dm_db_partition_stats (e.g., a newly created empty table where stats haven't updated).
ORDER BY: Sorts the results to show the largest tables first, which is often the most useful view.
Optional Total: The commented-out section shows how you could wrap the main query to get a grand total for all listed tables.*/